"""Generate the literature survey PDF in the tabular format of final.pdf."""
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether

OUT = "docs/literature-survey-explainable-ai-weather-busts.pdf"
styles = getSampleStyleSheet()
body = ParagraphStyle("Body", parent=styles["Normal"], fontName="Times-Roman", fontSize=9.2, leading=11.2, alignment=TA_JUSTIFY, spaceAfter=5)
title = ParagraphStyle("Title", parent=body, fontName="Times-Bold", fontSize=13, leading=16, alignment=TA_CENTER, spaceAfter=11)
h1 = ParagraphStyle("H1", parent=body, fontName="Times-Bold", fontSize=11, leading=13, spaceBefore=5, spaceAfter=6)
small = ParagraphStyle("Small", parent=body, fontSize=6.6, leading=7.8, spaceAfter=0)
smallc = ParagraphStyle("SmallC", parent=small, fontName="Times-Bold", alignment=TA_CENTER)
ref = ParagraphStyle("Ref", parent=body, fontSize=8.15, leading=10.1, leftIndent=0, firstLineIndent=0, spaceAfter=4)

rows = [
("[1] Potvin et al. (2024)", "Predicts whether convection-allowing ensemble forecasts will have poor, fair, or good skill.", "Ordinal logistic regression and random forest; percentile-defined skill classes; predictor reduction.", "106 WoFS cases (2017–2021), 323 initial predictors, radar verification.", "Reduced 10–15-predictor models substantially outperform persistence and spread baselines.", "Closest base paper: directly learns a forecast-of-forecast-skill and prioritizes operational explainability."),
("[2] Rodwell et al. (2013)", "Establishes the modern concept and synoptic causes of medium-range forecast busts.", "Composite analysis of ECMWF day-6 Z500 busts; spread–error and flow-regime diagnosis.", "22 years of fixed-system ERA-Interim forecasts; several hundred European busts.", "Busts align with blocking, an upstream Rockies trough, high CAPE and only partly increased spread.", "Defines the scientific problem, but at continental Z500 scale rather than district surface impacts."),
("[3] Parsons et al. (2019)", "Examines how continental mesoscale convection contributes to downstream global-model busts.", "Case study, potential-vorticity diagnostics and Rossby-wave error-propagation analysis.", "June 2015 operational and reanalysis forecasts plus observations.", "MCS-related diabatic errors can amplify ridges and alter downstream wave evolution.", "Motivates CAPE, tendencies and multivariate predictors for bust diagnosis."),
("[4] Guan et al. (2022)", "Documents the GEFSv12 reforecast archive used for training and calibration.", "System description and evaluation of Z500, precipitation, temperature, storms and MJO.", "GEFSv12 reforecasts, 1989–2019; Phase 2 has 5 daily members at ~0.25°.", "GEFSv12 is similar or superior to earlier GEFS reforecasts across major fields.", "Provides the long, model-consistent hindcast foundation needed to learn rare forecast failures."),
("[5] Hamill et al. (2022)", "Describes the reanalysis that initializes GEFSv12 reforecasts.", "Hybrid ensemble data assimilation and quality comparisons with CFSR/operational analyses.", "Global GEFSv12 reanalysis, 2000–2019.", "Improved analysis quality and suitable internally consistent initial states for reforecasting.", "Supports provenance and clarifies that reanalysis truth and initialization are imperfect."),
("[6] Dube et al. (2016)", "Verifies medium-range probabilistic rainfall forecasts over India.", "Brier score/decomposition, BSS, reliability diagrams and ROC/AUC across thresholds.", "NGEFS, monsoons 2012–2014; NMSG, CPC-RFE2.0 and TRMM observations.", "Skill and reliability depend on lead, threshold and verifying dataset.", "Establishes India-specific probabilistic verification and the need for multiple truth products."),
("[7] Chakraborty et al. (2021)", "Assesses NEPS-G skill for Indian summer-monsoon rainfall and circulation.", "BSS, CRPSS and extreme-event probability verification against climatology.", "NEPS-G JJAS 2018; IMERG, IMDAA and reanalysis references.", "Positive skill for light–moderate precipitation and wind persists to about day 7.", "Shows both the value and lead-dependent limits of Indian ensemble guidance."),
("[8] Dube et al. (2022)", "Separates spatial sources of ensemble rainfall error over India.", "Contiguous Rain Areas; decomposition into displacement, volume and pattern error.", "NEPS-G and observations over India, monsoons 2018–2020; 10–80 mm/day thresholds.", "Pattern error contributes roughly 70% overall; behavior changes for heavier rainfall.", "Warns that district-mean absolute error can hide displacement and structural error."),
("[9] Roy Bhowmik & Durai (2012)", "Develops operational district-level medium-range rainfall guidance for India.", "Weighted multi-model ensemble using global NWP outputs and district aggregation.", "Operational model forecasts and Indian district rainfall observations.", "MME improves usable district rainfall guidance, with regional and lead-time variation.", "Direct precedent for district-scale delivery, but not for predicting or explaining bust probability."),
("[10] Rasp & Lerch (2018)", "Uses neural networks to postprocess ensemble temperature forecasts.", "Distributional regression with auxiliary predictors and station embeddings; EMOS comparison.", "Ensemble forecasts and station observations over Germany.", "Neural postprocessing improves probabilistic skill and reveals useful predictor structure.", "Supports learned nonlinear postprocessing while emphasizing calibrated distributions."),
("[11] Gneiting & Raftery (2007)", "Provides the statistical basis for evaluating probabilistic forecasts.", "Theory and review of strictly proper scoring rules, calibration and sharpness.", "General probabilistic forecasting framework.", "Proper scores reward honest probabilities and permit coherent model comparison.", "Justifies Brier/CRPS-based evaluation rather than accuracy or ROC-AUC alone."),
("[12] Bröcker & Smith (2007)", "Clarifies uncertainty, reliability and resolution in probability-score decompositions.", "General decomposition of proper scores and diagnostic interpretation.", "Analytical framework with forecast examples.", "Separates calibration from discrimination and irreducible uncertainty.", "Supports reliability analysis of district bust probabilities."),
("[13] Lundberg & Lee (2017)", "Introduces SHAP as a unified additive feature-attribution framework.", "Game-theoretic Shapley values unifying multiple local explanation methods.", "Multiple benchmark models and datasets.", "Provides local accuracy, missingness and consistency properties.", "Core basis for per-district explanations, but attribution is not causation."),
("[14] Lundberg et al. (2020)", "Makes exact, fast SHAP analysis practical for tree ensembles.", "TreeSHAP, interaction effects and global aggregation of local explanations.", "Large clinical tree-model case studies.", "Efficiently exposes nonlinear effects and feature interactions.", "Strong methodological fit for XGBoost; correlated meteorological inputs still complicate interpretation."),
("[15] Chen & Guestrin (2016)", "Introduces the scalable gradient-boosted tree system used by the project.", "Regularized boosting, sparsity-aware learning and approximate split finding.", "Broad classification/regression benchmarks.", "High predictive performance with efficient training and inference.", "Supports operational tabular modelling over heterogeneous district, lead and ensemble features."),
("[16] Dutta & Pal (2022)", "Explains ML prediction of pre-monsoon thunderstorms over Kolkata.", "XGBoost and logistic regression interpreted with local/global SHAP.", "Meteorological predictors for pre-monsoon cumulonimbus events over Kolkata.", "Both models identify CAPE as dominant, while other rankings differ by model.", "India-specific evidence that explanations can test meteorological plausibility and model dependence."),
("[17] Silva et al. (2022)", "Uses explainable ML to diagnose Earth-system-model errors.", "XGBoost error prediction with SHAP attribution.", "Earth-system-model fields and lightning-flash errors.", "Attributions connect errors to convection and surface heterogeneity.", "Closest methodological precedent for using SHAP to characterize model error rather than weather itself."),
("[18] Daif et al. (2025)", "Compares explainable boosting models for multi-horizon temperature prediction.", "AdaBoost, XGBoost, CatBoost and LightGBM with SHAP and LIME.", "Maximum/minimum temperature data at six horizons from same day to 30 days.", "CatBoost performs best; skill declines with lead; SHAP/LIME expose drivers.", "Supports horizon-aware XAI but studies forecast values, not NWP failure probabilities."),
("[19] Price et al. (2025)", "Demonstrates probabilistic ML medium-range ensemble prediction (GenCast).", "Conditional diffusion model producing global 15-day ensembles.", "ERA5 training; comparison with ECMWF ENS over 1,320 targets.", "Reports greater skill than ENS on most evaluated targets and stronger extremes/track prediction.", "Shows the field's shift to probabilistic ML; does not replace local confidence diagnostics for an issued forecast."),
("[20] Hersbach et al. (2020)", "Documents ERA5, the principal verification/reanalysis product.", "4D-Var reanalysis with uncertainty information and extensive observation assimilation.", "Global hourly atmosphere, land and ocean-wave fields from 1979 onward.", "Higher-resolution, improved reanalysis widely used for weather verification.", "Enables consistent gridded truth, while product disagreement places a floor under bust labels."),
]

refs = [
"[1] Potvin, C. K., et al. (2024). Using machine learning to predict convection-allowing ensemble forecast skill: Evaluation with the NSSL Warn-on-Forecast System. <i>Artificial Intelligence for the Earth Systems, 3</i>, e230106. https://doi.org/10.1175/AIES-D-23-0106.1",
"[2] Rodwell, M. J., et al. (2013). Characteristics of occasional poor medium-range weather forecasts for Europe. <i>Bulletin of the American Meteorological Society, 94</i>(9), 1393–1405. https://doi.org/10.1175/BAMS-D-12-00099.1",
"[3] Parsons, D. B., Lillo, S. P., Rattray, C. P., Bechtold, P., Rodwell, M. J., & Bruce, C. M. (2019). The role of continental mesoscale convective systems in forecast busts within global weather prediction systems. <i>Atmosphere, 10</i>(11), 681. https://doi.org/10.3390/atmos10110681",
"[4] Guan, H., et al. (2022). GEFSv12 reforecast dataset for supporting subseasonal and hydrometeorological applications. <i>Monthly Weather Review, 150</i>(3), 647–665. https://doi.org/10.1175/MWR-D-21-0245.1",
"[5] Hamill, T. M., et al. (2022). The reanalysis for the Global Ensemble Forecast System, version 12. <i>Monthly Weather Review, 150</i>(1), 59–79. https://doi.org/10.1175/MWR-D-21-0023.1",
"[6] Dube, A., Ashrit, R., Singh, H., Iyengar, G., & Rajagopal, E. N. (2016). Verification of medium range probabilistic rainfall forecasts over India. <i>Pure and Applied Geophysics, 173</i>, 2489–2510. https://doi.org/10.1007/s00024-016-1278-z",
"[7] Chakraborty, P., Sarkar, A., Bhatla, R., & Singh, R. (2021). Assessing the skill of NCMRWF global ensemble prediction system in predicting Indian summer monsoon during 2018. <i>Atmospheric Research, 251</i>, 105255. https://doi.org/10.1016/j.atmosres.2020.105255",
"[8] Dube, A., Karunasagar, S., Ashrit, R., & Mitra, A. K. (2022). Spatial verification of ensemble rainfall forecasts over India. <i>Atmospheric Research, 273</i>, 106169. https://doi.org/10.1016/j.atmosres.2022.106169",
"[9] Roy Bhowmik, S. K., & Durai, V. R. (2012). Development of multimodel ensemble based district level medium range rainfall forecast system for Indian region. <i>Journal of Earth System Science, 121</i>, 273–285. https://doi.org/10.1007/s12040-012-0160-1",
"[10] Rasp, S., & Lerch, S. (2018). Neural networks for postprocessing ensemble weather forecasts. <i>Monthly Weather Review, 146</i>(11), 3885–3900. https://doi.org/10.1175/MWR-D-18-0187.1",
"[11] Gneiting, T., & Raftery, A. E. (2007). Strictly proper scoring rules, prediction, and estimation. <i>Journal of the American Statistical Association, 102</i>(477), 359–378. https://doi.org/10.1198/016214506000001437",
"[12] Bröcker, J., & Smith, L. A. (2007). Increasing the reliability of reliability diagrams. <i>Weather and Forecasting, 22</i>(3), 651–661. https://doi.org/10.1175/WAF993.1",
"[13] Lundberg, S. M., & Lee, S.-I. (2017). A unified approach to interpreting model predictions. In <i>Advances in Neural Information Processing Systems 30</i>, 4765–4774. https://proceedings.neurips.cc/paper/7062-a-unified-approach-to-interpreting-model-predictions",
"[14] Lundberg, S. M., et al. (2020). From local explanations to global understanding with explainable AI for trees. <i>Nature Machine Intelligence, 2</i>, 56–67. https://doi.org/10.1038/s42256-019-0138-9",
"[15] Chen, T., & Guestrin, C. (2016). XGBoost: A scalable tree boosting system. In <i>Proceedings of the 22nd ACM SIGKDD Conference</i>, 785–794. https://doi.org/10.1145/2939672.2939785",
"[16] Dutta, S., & Pal, S. K. (2022). Interpretation of black box for short-term predictions of pre-monsoon cumulonimbus cloud events over Kolkata. <i>SN Computer Science, 3</i>, 352. https://doi.org/10.1007/s42979-022-01255-x",
"[17] Silva, S. J., Keller, C. A., & Hardin, J. (2022). Using an explainable machine learning approach to characterize Earth system model errors: Application of SHAP analysis to modeling lightning flash occurrence. <i>Journal of Advances in Modeling Earth Systems, 14</i>, e2021MS002881. https://doi.org/10.1029/2021MS002881",
"[18] Daif, N., Di Nunno, F., Granata, F., et al. (2025). Forecasting maximal and minimal air temperatures using explainable machine learning: SHAP versus LIME. <i>Stochastic Environmental Research and Risk Assessment, 39</i>, 2551–2581. https://doi.org/10.1007/s00477-025-02984-4",
"[19] Price, I., et al. (2025). Probabilistic weather forecasting with machine learning. <i>Nature, 637</i>, 84–90. https://doi.org/10.1038/s41586-024-08252-9",
"[20] Hersbach, H., et al. (2020). The ERA5 global reanalysis. <i>Quarterly Journal of the Royal Meteorological Society, 146</i>(730), 1999–2049. https://doi.org/10.1002/qj.3803",
]

def footer(canvas, doc):
    canvas.saveState(); canvas.setFont("Times-Roman", 7)
    canvas.drawCentredString(A4[0]/2, 9*mm, str(doc.page)); canvas.restoreState()

doc = SimpleDocTemplate(OUT, pagesize=A4, rightMargin=13*mm, leftMargin=13*mm, topMargin=13*mm, bottomMargin=15*mm, title="Literature Survey — Explainable AI for District-Level Prediction of Medium-Range Weather Forecast Busts over India", author="Sanket research project")
story=[]
story.append(Paragraph("Explainable AI for District-Level Prediction of Medium-Range Weather Forecast Busts over India", title))
story.append(Paragraph("1. BASE PAPER", h1))
story.append(Paragraph("<b>Base paper:</b> Potvin, C. K., et al. (2024), “Using Machine Learning to Predict Convection-Allowing Ensemble Forecast Skill: Evaluation with the NSSL Warn-on-Forecast System.”", body))
story.append(Paragraph("<b>Why this is the best base paper:</b> It is the closest peer-reviewed study to the proposed research objective because it does not attempt to replace numerical weather prediction; instead, it learns when an already-issued ensemble forecast is likely to perform poorly. It defines percentile-based skill classes, compares machine learning against persistence and ensemble-spread baselines, reduces the predictor set for operational use, and treats explainability as a design constraint. The proposed work extends this idea from localized 0–3 h convective forecasts in the United States to district-level, Day 1–10 surface-weather bust probabilities across India, using a long GEFSv12 reforecast archive and local SHAP explanations.", body))
story.append(Paragraph("<b>Project analysis:</b> Sanket aggregates NOAA GEFSv12 forecasts and ERA5 verification to 666 Indian districts using one area-overlap weight table. For eight surface variables and lead days 1–10, a variable-specific XGBoost regressor estimates bias-corrected absolute error; an out-of-fold classifier maps error evidence to a bust probability, where a bust exceeds a variable-specific training-set 90th-percentile threshold. Predictors include ensemble spread/member count, run-to-run jumps, lagged ensembles, tendencies, cross-variable forecasts, season, geography and historical district frequency. TreeSHAP supplies local attributions. Evaluation uses held-out years and a climatology/lead/spread/EMOS/IDR/analog baseline ladder with Brier skill, ROC-AUC, SEDI, reliability decomposition, economic value and conformal coverage. This is therefore confidence forecasting and error diagnosis—not a new weather forecast.", body))
story.append(Paragraph("<b>Proposed research gap:</b> Forecast-bust research mainly diagnoses continental upper-air failures after the event; Indian studies mainly verify rainfall or produce district forecasts; XAI-weather studies mainly explain the predicted weather quantity. The missing integration is an operationally usable, calibrated and locally explained probability that a specific medium-range forecast will fail, for multiple surface variables at district scale over India. A defensible contribution must also address correlated-feature SHAP, temporal leakage, nonstationarity, rare-event calibration, regional/seasonal equity, observation uncertainty, spatial displacement error and explanation stability. The repository audit already identifies two threats that must be resolved before final claims: a realised-error lag unavailable at issue time in the currently served run, and historical rainfall-label contamination/misalignment. These caveats strengthen the research design by making leakage-free retraining and multi-year evaluation explicit requirements.", body))
story.append(Paragraph("2. LITERATURE SURVEY", h1))
story.append(Paragraph("The survey synthesizes work on forecast busts, forecast-of-forecast-skill, Indian district and ensemble verification, reforecast/reanalysis data, probabilistic scoring, post-processing and explainable machine learning. Results below are those reported by the cited studies; they are not claimed as results of the proposed system.", body))
header=[Paragraph("Reference",smallc),Paragraph("Contribution",smallc),Paragraph("Methodology",smallc),Paragraph("Data set",smallc),Paragraph("Results",smallc),Paragraph("Key Findings",smallc)]
data=[header]+[[Paragraph(x,small) for x in r] for r in rows]
t=Table(data, colWidths=[22*mm,31*mm,34*mm,31*mm,32*mm,34*mm], repeatRows=1, hAlign='LEFT')
t.setStyle(TableStyle([
('GRID',(0,0),(-1,-1),0.35,colors.HexColor('#777777')),('BACKGROUND',(0,0),(-1,0),colors.HexColor('#E7E7E7')),
('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),2.2),('RIGHTPADDING',(0,0),(-1,-1),2.2),('TOPPADDING',(0,0),(-1,-1),2.2),('BOTTOMPADDING',(0,0),(-1,-1),2.2),
]))
story.append(t)
story.append(PageBreak()); story.append(Paragraph("3. SYNTHESIS AND RESEARCH POSITIONING", h1))
story.append(Paragraph("<b>Convergence in the literature.</b> Three findings recur. First, ensemble spread is informative but insufficient: both classical bust studies and modern forecast-skill prediction show a residual gap between predicted uncertainty and realised error. Second, probabilistic quality is multidimensional; discrimination must be accompanied by reliability and proper scores. Third, explanation is most useful when it is local, physically checked and tied to operational action. These findings support a two-stage system that predicts error magnitude and then calibrated bust probability, benchmarked against spread-only and climatological models.", body))
story.append(Paragraph("<b>Distinct contribution.</b> Sanket combines dimensions that prior studies treat separately: (i) tail-error prediction rather than direct weather prediction, (ii) daily district-scale output for all India, (iii) eight surface variables across Day 1–10, (iv) consistent polygon-weighted forecast and verification fields, (v) long reforecast training data, and (vi) local TreeSHAP narratives. Its novelty is consequently the problem formulation and operational integration, not the use of XGBoost or SHAP alone.", body))
story.append(Paragraph("<b>Required validation.</b> The paper should report leakage-free rolling or blocked temporal evaluation with a Day-10 embargo; thresholds fitted only on training data; multi-year 2017–2019 tests; calibration curves and Brier decomposition by variable, lead, season and region; bootstrap confidence intervals grouped by forecast cycle; comparison with climatology, lead-only, spread-only and calibrated ensemble baselines; sensitivity to ERA5 versus an independent/gauge truth; SHAP stability under correlated-feature grouping; and case studies that distinguish useful warning from merely large climatological bias. Claims should be limited to leads available for each variable and should not interpret SHAP as causal evidence.", body))
story.append(Paragraph("4. REFERENCES", h1))
for x in refs: story.append(Paragraph(x,ref))
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
